### ISSUE TITLE
Enable Metal Hud (show FPS) option toggled on after closing and re-opening launcher

### ISSUE THREAD

**Issue by barrghbossa** [tairasu/TurtleSilicon#41]
The setting to "Enable Metal Hud (show FPS)" in the Options sub-menu is always re-enabled after closing and re-opening the launcher.

**Comment by tairasu** [comment]
sorry about that. this has been fixed now. the metal hud will also be turned off by default

**Comment by peterklingelhofer** [comment]
@tairasu I tried the latest release, it's still not remembering my preference for Metal HUD and it is not turned off by default unfortunately

**Comment by barrghbossa** [comment]
@peterklingelhofer I reported this bug for the current version 1.2.4, so the next release should include this fix.

**Comment by peterklingelhofer** [comment]
@barrghbossa my fault, I misaligned the commit date and latest release date!

**Comment by tairasu** [comment]
this fix has been added to v1.3.0
